<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Cordis\Cordis.csproj" />
    <ProjectReference Include="..\Dsh.Core\Dsh.Core.csproj" />
    <ProjectReference Include="..\Dsh.Llm\Dsh.Llm.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.11" />
    <PackageReference Include="SQLitePCLRaw.provider.sqlite3" Version="3.0.5" />
  </ItemGroup>

</Project>
