<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Cordis\Cordis.csproj" />
    <ProjectReference Include="..\Dsh.Core\Dsh.Core.csproj" />
    <ProjectReference Include="..\Dsh.Llm\Dsh.Llm.csproj" />
    <ProjectReference Include="..\Dsh.Subagent\Dsh.Subagent.csproj" />
    <ProjectReference Include="..\Dsh.Tools\Dsh.Tools.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Jint" Version="4.16.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>