using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Dsh.Plugins.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class DshPluginCatalogGenerator : IIncrementalGenerator
{
    private const string InterfaceMetadataName = "Dsh.Plugins.IDshPlugin";
    private const string AttributeMetadataName = "Dsh.Plugins.DshPluginAttribute";
    private const string HintName = "DshPluginCatalog.g.cs";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var entries = context.CompilationProvider.Select(static (compilation, _) => GetPluginEntries(compilation));
        context.RegisterSourceOutput(entries, static (context, value) =>
        {
            context.AddSource(HintName, SourceText.From(GenerateSource(value), Encoding.UTF8));
        });
    }

    private static List<PluginEntry> GetPluginEntries(Compilation compilation)
    {
        var pluginInterface = compilation.GetTypeByMetadataName(InterfaceMetadataName);
        var pluginAttribute = compilation.GetTypeByMetadataName(AttributeMetadataName);
        if (pluginInterface is null || pluginAttribute is null)
            return [];

        var assemblies = new List<IAssemblySymbol> { compilation.Assembly };
        assemblies.AddRange(compilation.SourceModule.ReferencedAssemblySymbols);

        var entries = new List<PluginEntry>();
        foreach (var assembly in assemblies.Distinct<IAssemblySymbol>(SymbolEqualityComparer.Default))
        {
            var packages = assembly.GetAttributes()
                .Where(attribute => attribute.AttributeClass is not null && SymbolEqualityComparer.Default.Equals(attribute.AttributeClass, pluginAttribute))
                .Select(attribute => attribute.ConstructorArguments.FirstOrDefault().Value as string)
                .Where(package => !string.IsNullOrEmpty(package))
                .ToList();
            if (packages.Count == 0)
                continue;

            foreach (var type in EnumerateTypes(assembly.GlobalNamespace))
            {
                if (type.TypeKind != TypeKind.Class || type.IsAbstract || type.IsStatic)
                    continue;
                if (!ImplementsPlugin(type, pluginInterface))
                    continue;
                foreach (var package in packages)
                {
                    entries.Add(new PluginEntry(
                        package!,
                        type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));
                }
            }
        }

        return entries
            .Distinct()
            .OrderBy(entry => entry.Package, System.StringComparer.Ordinal)
            .ThenBy(entry => entry.TypeName, System.StringComparer.Ordinal)
            .ToList();
    }

    private static bool ImplementsPlugin(INamedTypeSymbol type, INamedTypeSymbol pluginInterface)
    {
        for (var current = type; current is not null; current = current.BaseType)
        {
            if (current.AllInterfaces.Any(interfaceType => SymbolEqualityComparer.Default.Equals(interfaceType, pluginInterface)))
                return true;
        }

        return false;
    }

    private static IEnumerable<INamedTypeSymbol> EnumerateTypes(INamespaceSymbol namespaceSymbol)
    {
        foreach (var type in namespaceSymbol.GetTypeMembers())
            yield return type;
        foreach (var child in namespaceSymbol.GetNamespaceMembers())
        {
            foreach (var type in EnumerateTypes(child))
                yield return type;
        }
    }

    private static string GenerateSource(List<PluginEntry> entries)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.Diagnostics.CodeAnalysis;");
        builder.AppendLine();
        builder.AppendLine("namespace Dsh.Plugins.Generated");
        builder.AppendLine("{");
        builder.AppendLine("    public sealed class PluginEntry");
        builder.AppendLine("    {");
        builder.AppendLine("        public PluginEntry(string package, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] Type implementation)");
        builder.AppendLine("        {");
        builder.AppendLine("            Package = package;");
        builder.AppendLine("            Implementation = implementation;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public string Package { get; }");
        builder.AppendLine("        [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)]");
        builder.AppendLine("        public Type Implementation { get; }");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public static class DshPluginCatalog");
        builder.AppendLine("    {");
        builder.AppendLine("        public static IReadOnlyList<PluginEntry> GetPlugins()");
        builder.AppendLine("        {");
        builder.AppendLine($"            var list = new List<PluginEntry>({entries.Count});");
        foreach (var entry in entries)
        {
            builder.AppendLine($"            list.Add(new PluginEntry(\"{entry.Package}\", typeof({entry.TypeName})));");
        }

        builder.AppendLine("            return list;");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("namespace Dsh.Launcher");
        builder.AppendLine("{");
        builder.AppendLine("    public static class PluginRoot");
        builder.AppendLine("    {");
        builder.AppendLine("        public static void EnsureRooted()");
        builder.AppendLine("        {");
        builder.AppendLine("            _ = Dsh.Plugins.Generated.DshPluginCatalog.GetPlugins();");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private sealed class PluginEntry
    {
        public PluginEntry(string package, string typeName)
        {
            Package = package;
            TypeName = typeName;
        }

        public string Package { get; }

        public string TypeName { get; }
    }
}