using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace Dsh.Plugins.Generator;

public sealed partial class DshPluginCatalogGenerator
{
    private static class Templates
    {
        public static SourceText RenderManifest(IReadOnlyList<PluginRegistration> registrations, IReadOnlyList<string> sharedDependencies)
            => RenderCatalogLike("DshPluginManifest", registrations, selfRegister: false, bootstraps: [], sharedDependencies);

        public static SourceText RenderCatalog(
            IReadOnlyList<PluginRegistration> registrations,
            IReadOnlyList<string> bootstraps)
            => RenderCatalogLike("DshPluginCatalog", registrations, selfRegister: true, bootstraps, sharedDependencies: null);

        /** 汇编级显式注册桥:宿主静态引用后,源生成 JSON 上下文与初始化方法在裁剪/AOT 下保留并生效。 */
        public static SourceText RenderBootstrap(string namespaceName, BootstrapSpec spec)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("#nullable enable");
            builder.AppendLine();
            builder.AppendLine($"namespace {namespaceName}.Generated");
            builder.AppendLine("{");
            builder.AppendLine("    public static class DshPluginBootstrap");
            builder.AppendLine("    {");
            builder.AppendLine("        public static void Register()");
            builder.AppendLine("        {");
            foreach (var initializer in spec.Initializers)
                builder.AppendLine($"            {initializer}();");
            foreach (var context in spec.JsonContexts)
                builder.AppendLine($"            global::Dsh.Llm.DshJson.RegisterResolver({context}.Default);");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return SourceText.From(builder.ToString(), Encoding.UTF8);
        }

        private static SourceText RenderCatalogLike(
            string className,
            IReadOnlyList<PluginRegistration> registrations,
            bool selfRegister,
            IReadOnlyList<string> bootstraps,
            IReadOnlyList<string>? sharedDependencies)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("#nullable enable");
            if (selfRegister)
                builder.AppendLine("#pragma warning disable CA2255");
            builder.AppendLine();
            builder.AppendLine("namespace Dsh.Plugins.Generated");
            builder.AppendLine("{");
            builder.AppendLine($"    public static class {className}");
            builder.AppendLine("    {");
            builder.AppendLine("        public static global::System.Collections.Generic.IReadOnlyList<global::Dsh.Plugins.DshPluginRegistration> Registrations()");
            builder.AppendLine("            => new global::Dsh.Plugins.DshPluginRegistration[]");
            builder.AppendLine("            {");
            foreach (var registration in registrations)
                builder.AppendLine($"                {Registration(registration)}");
            builder.AppendLine("            };");
            if (sharedDependencies is not null)
            {
                builder.AppendLine();
                builder.AppendLine("        public static global::System.Collections.Generic.IReadOnlyList<string> SharedDependencies()");
                builder.AppendLine("            => new string[]");
                builder.AppendLine("            {");
                foreach (var dependency in sharedDependencies)
                    builder.AppendLine($"                {Literal(dependency)},");
                builder.AppendLine("            };");
            }
            if (selfRegister)
            {
                builder.AppendLine();
                builder.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
                builder.AppendLine("        internal static void RegisterAll()");
                builder.AppendLine("        {");
                foreach (var bootstrap in bootstraps.OrderBy(name => name, StringComparer.Ordinal))
                    builder.AppendLine($"            {bootstrap}.Register();");
                builder.AppendLine("            foreach (var registration in Registrations())");
                builder.AppendLine("                global::Dsh.Plugins.DshPluginCatalogRegistry.Register(registration);");
                builder.AppendLine("        }");
            }
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return SourceText.From(builder.ToString(), Encoding.UTF8);
        }

        private static string Registration(PluginRegistration registration)
        {
            var package = Literal(registration.Package);
            var create = registration.NeedsPackage
                ? $"static () => new {registration.TypeName}({package})"
                : $"static () => new {registration.TypeName}()";
            var entry = registration.Entry is null ? "null" : Literal(registration.Entry);
            return $"new({package}, global::Dsh.Plugins.PluginDescriptor.CurrentVersion, {create}, {entry}),";
        }

        private static string Literal(string value)
            => "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
    }
}
