<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Dsh.Plugins.Abstractions\Dsh.Plugins.Abstractions.csproj" />
    <ProjectReference Include="..\Dsh.Interaction\Dsh.Interaction.csproj" />
    <ProjectReference Include="..\Dsh.Boot\Dsh.Boot.csproj" />
    <ProjectReference Include="..\Dsh.Core\Dsh.Core.csproj" />
    <ProjectReference Include="..\Dsh.Llm\Dsh.Llm.csproj" />
    <ProjectReference Include="..\..\Cordis\Cordis.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol" Version="2.2.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>