<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Cordis\Cordis.csproj" />
    <ProjectReference Include="..\Dsh.Core\Dsh.Core.csproj" />
    <ProjectReference Include="..\Dsh.Tools\Dsh.Tools.csproj" />
    <ProjectReference Include="..\Dsh.Jobs\Dsh.Jobs.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
