<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Cordis\Cordis.csproj" />
    <ProjectReference Include="..\Dsh.Plugins.Abstractions\Dsh.Plugins.Abstractions.csproj" />
    <ProjectReference Include="..\Dsh.Boot\Dsh.Boot.csproj" />
    <ProjectReference Include="..\Dsh.Sdk\Dsh.Sdk.csproj" />
  </ItemGroup>

</Project>
