using System.Reflection;
using System.Runtime.Loader;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Dsh.Ptc;

public sealed record PtcCompilation(byte[]? Assembly, IReadOnlyList<string> Errors);

/** 在脚本宿主子进程内用 Roslyn 把模型程序编译为内存程序集; 诊断在执行前拦截。 */
public static class PtcProgramCompiler
{
    private const int MaxDiagnostics = 20;

    private static readonly Lazy<IReadOnlyList<MetadataReference>> References = new(() =>
    {
        var trusted = (AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES") as string)?.Split(Path.PathSeparator) ?? [];
        return trusted
            .Where(path => path.EndsWith(".dll", StringComparison.OrdinalIgnoreCase))
            .Select(path => (MetadataReference)MetadataReference.CreateFromFile(path))
            .ToList();
    });

    public static PtcCompilation Compile(string program, IReadOnlyList<string> bindings)
    {
        var tree = CSharpSyntaxTree.ParseText(PtcProgramSource.Build(program, bindings), new CSharpParseOptions(LanguageVersion.Latest));
        var options = new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
            .WithOptimizationLevel(OptimizationLevel.Debug)
            .WithNullableContextOptions(NullableContextOptions.Disable);
        var compilation = CSharpCompilation.Create("dsh-ptc-program", [tree], References.Value, options);
        using var stream = new MemoryStream();
        var result = compilation.Emit(stream);
        if (result.Success)
            return new PtcCompilation(stream.ToArray(), []);
        var errors = result.Diagnostics
            .Where(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .Select(diagnostic => diagnostic.ToString())
            .Take(MaxDiagnostics)
            .ToList();
        return new PtcCompilation(null, errors);
    }

    private static class PtcProgramSource
    {
        public static string Build(string program, IReadOnlyList<string> bindings)
        {
            var builder = new StringBuilder(Header);
            if (bindings.Count > 0)
            {
                builder.Append("public static class tools\n{\n");
                foreach (var name in bindings.OrderBy(name => name, StringComparer.Ordinal))
                    AppendBinding(builder, name);
                builder.Append("}\n\n");
            }
            builder.Append("public static class __Program\n{\n");
            builder.Append("    public static async Task<JsonNode?> Run()\n    {\n");
            builder.Append(program);
            builder.Append("\n        return null;\n    }\n}\n");
            return builder.ToString();
        }

        private static void AppendBinding(StringBuilder builder, string name)
        {
            builder.Append("    public static async Task<JsonNode?> ").Append(name).Append("(JsonObject args)\n    {\n");
            builder.Append("        var envelope = JsonNode.Parse(await __PtcBridge.Call(\"").Append(name).Append("\", args))!;\n");
            builder.Append("        if (!envelope[\"ok\"]!.GetValue<bool>())\n");
            builder.Append("            throw new ToolCallError(\"").Append(name).Append("\", envelope[\"message\"]?.GetValue<string>() ?? \"tool call failed\");\n");
            builder.Append("        return envelope[\"value\"];\n    }\n");
        }

        private const string Header = """
            // <auto-generated />
            using System;
            using System.Text.Json;
            using System.Text.Json.Nodes;
            using System.Threading.Tasks;
            using System.Collections.Generic;
            using System.Linq;

            public sealed class ToolCallError : Exception
            {
                public ToolCallError(string toolName, string message) : base(message) => ToolName = toolName;
                public string ToolName { get; }
            }

            public static class __PtcBridge
            {
                public static Func<string, JsonObject, Task<string>> Call = null!;
            }

            """;
    }
}

/** 模型程序程序集的独立可回收加载上下文; 未命中的程序集回退到默认上下文解析 BCL。 */
internal sealed class PtcProgramLoadContext() : AssemblyLoadContext("dsh-ptc-program", isCollectible: true)
{
    protected override Assembly? Load(AssemblyName assemblyName)
    {
        try
        {
            return Default.LoadFromAssemblyName(assemblyName);
        }
        catch (FileNotFoundException)
        {
            return null;
        }
    }
}
